#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : warlock
Version  : 1.3.3
Release  : 39
URL      : https://files.pythonhosted.org/packages/c2/36/178b26a338cd6d30523246da4721b1114306f588deb813f3f503052825ee/warlock-1.3.3.tar.gz
Source0  : https://files.pythonhosted.org/packages/c2/36/178b26a338cd6d30523246da4721b1114306f588deb813f3f503052825ee/warlock-1.3.3.tar.gz
Summary  : Python object model built on JSON schema and JSON patch.
Group    : Development/Tools
License  : Apache-2.0
Requires: warlock-license = %{version}-%{release}
Requires: warlock-python = %{version}-%{release}
Requires: warlock-python3 = %{version}-%{release}
Requires: jsonpatch
Requires: jsonschema
Requires: six
BuildRequires : buildreq-distutils3
BuildRequires : jsonpatch
BuildRequires : jsonpointer
BuildRequires : jsonschema
BuildRequires : py
BuildRequires : pytest
BuildRequires : python3-dev
BuildRequires : six
BuildRequires : warlock

%description
# Warlock — self-validating Python objects using JSON schema
[![PyPI](https://img.shields.io/pypi/v/warlock.svg)][warlock]
[![PyPI - Python Version](https://img.shields.io/pypi/pyversions/warlock.svg)][warlock]
[![PyPI - Downloads](https://img.shields.io/pypi/dw/warlock.svg)][pypistats]

%package license
Summary: license components for the warlock package.
Group: Default

%description license
license components for the warlock package.


%package python
Summary: python components for the warlock package.
Group: Default
Requires: warlock-python3 = %{version}-%{release}

%description python
python components for the warlock package.


%package python3
Summary: python3 components for the warlock package.
Group: Default
Requires: python3-core
Provides: pypi(warlock)
Requires: pypi(jsonpatch)
Requires: pypi(jsonschema)
Requires: pypi(six)

%description python3
python3 components for the warlock package.


%prep
%setup -q -n warlock-1.3.3
cd %{_builddir}/warlock-1.3.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1583533073
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
py.test-2.7 || :
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/warlock
cp %{_builddir}/warlock-1.3.3/LICENSE %{buildroot}/usr/share/package-licenses/warlock/2b8b815229aa8a61e483fb4ba0588b8b6c491890
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/warlock/2b8b815229aa8a61e483fb4ba0588b8b6c491890

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
