#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : warlock
Version  : 1.3.0
Release  : 35
URL      : https://files.pythonhosted.org/packages/2d/40/9f01a5e1574dab946598793351d59c86f58209d182d229aaa545abb98894/warlock-1.3.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/2d/40/9f01a5e1574dab946598793351d59c86f58209d182d229aaa545abb98894/warlock-1.3.0.tar.gz
Summary  : Python object model built on JSON schema and JSON patch.
Group    : Development/Tools
License  : Apache-2.0
Requires: warlock-license = %{version}-%{release}
Requires: warlock-python = %{version}-%{release}
Requires: warlock-python3 = %{version}-%{release}
Requires: jsonpatch
Requires: jsonschema
Requires: six
BuildRequires : buildreq-distutils3
BuildRequires : jsonpatch
BuildRequires : jsonpointer
BuildRequires : jsonschema
BuildRequires : py
BuildRequires : pytest
BuildRequires : python3-dev
BuildRequires : six
BuildRequires : warlock
Patch1: req.patch

%description
# Warlock
[![Build Status](https://travis-ci.org/bcwaldon/warlock.svg?branch=master)](https://travis-ci.org/bcwaldon/warlock)

%package license
Summary: license components for the warlock package.
Group: Default

%description license
license components for the warlock package.


%package python
Summary: python components for the warlock package.
Group: Default
Requires: warlock-python3 = %{version}-%{release}

%description python
python components for the warlock package.


%package python3
Summary: python3 components for the warlock package.
Group: Default
Requires: python3-core

%description python3
python3 components for the warlock package.


%prep
%setup -q -n warlock-1.3.0
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1554304975
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
py.test-2.7 || :
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/warlock
cp LICENSE.txt %{buildroot}/usr/share/package-licenses/warlock/LICENSE.txt
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/warlock/LICENSE.txt

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
